[Settings]
# 开启浏览器运行，若更新无数据可开启此模式，较消耗性能; 可选值: True, False | Enable browser execution, If there are no updates, this mode can be enabled, which consumes more performance; Optional values: True, False
open_driver = False
# 开启无结果频道分类，自动归类至底部; 可选值: True, False | Enable empty category, automatically classified to the bottom; Optional values: True, False
open_empty_category = False
# 开启分辨率过滤，低于最小分辨率（min_resolution）的接口将会被过滤，GUI用户需要手动安装FFmpeg，程序会自动调用FFmpeg获取接口分辨率，推荐开启，虽然会增加测速阶段耗时，但能更有效地区分是否可播放的接口，可选值：True, False | Enable resolution filtering, interfaces below the minimum resolution (min_resolution) will be filtered, GUI users need to manually install FFmpeg, the program will automatically call FFmpeg to obtain the interface resolution, it is recommended to enable, although it will increase the time-consuming of the speed measurement stage, but it can more effectively distinguish whether the interface can be played, optional values: True, False
open_filter_resolution = True
# 开启速率过滤，低于最小速率（min_speed）的接口将会被过滤; 可选值: True, False | Enable rate filtering, interfaces below the minimum rate (min_speed) will be filtered; Optional values: True, False
open_filter_speed = True
# 开启酒店源功能，关闭后所有酒店源工作模式都将关闭; 可选值: True, False | Enable hotel source function, after closing, all hotel source working modes will be closed; Optional values: True, False
open_hotel = False
# 开启 Foodie 酒店源工作模式; 可选值: True, False | Enable Foodie hotel source working mode; Optional values: True, False
open_hotel_foodie = True
# 开启 FOFA、ZoomEye 酒店源工作模式; 可选值: True, False | Enable FOFA, ZoomEye hotel source working mode; Optional values: True, False
open_hotel_fofa = False
# 开启保留所有检索结果，会保留非模板频道名称的结果，推荐手动维护时开启; 可选值: True, False | Enable to keep all search results, will keep the results of non-template channel names, it is recommended to enable when manually maintaining; Optional values: True, False